import csv


CASES_FILE = "cases.tsv"


cases = {}
with open(CASES_FILE, newline="") as f:
    reader = csv.DictReader(f, delimiter="\t")
    for row in reader:
        cases[row["case_id"]] = row


rule all:
    input:
        expand("../case_{case_id}/.galerna.done", case_id=cases.keys())


rule run_case:
    output:
        done="../case_{case_id}/.galerna.done"
    log:
        stdout="../case_{case_id}/galerna.out",
        stderr="../case_{case_id}/galerna.err"
    params:
        case_dir=lambda wildcards: cases[wildcards.case_id]["case_dir"],
        command=lambda wildcards: cases[wildcards.case_id]["command"]
    threads: 1
    shell:
        """
        cd {params.case_dir}
        {params.command} > {log.stdout} 2> {log.stderr}
        touch {output.done}
        """
